### PR TITLE
(feat):Add the ability to toggle the test scenarios for a clean UI

### PR DESCRIPTION
**Pull request by PeterNgTr**
### (feat):Add the ability to toggle the test scenarios for a clean UI

Screenshot 2019-11-28 at 13 09 10

### CODE REVIEW

**Comment by DavertMik** [comment]
Lot's of [ Toggle ] buttons doesn't seem like a clean  UI :)

**Comment by PeterNgTr** [comment]
> Lots of [ Toggle ] buttons doesn't seem like a clean UI :)

Better to show Toggle button on Feature level

Screenshot 2019-11-28 at 14 56 46

**Comment by DavertMik** [comment]
Anyway, I don't like the [ Toggle ] button. Toggle what? It doesn't explain.

But what if we will show a feature title and clicking the title will list all scenarios

**Comment by PeterNgTr** [comment]
@DavertMik one more try
Screenshot 2019-11-29 at 10 59 52

**Comment by DavertMik** [comment]
Should be fine now!

**Comment by DavertMik** [comment]
Sorry, I have to revert this. The design looks ok for mobile but looks bad for desktop. 
Selection_655
Not great.

**Pull request merged**
